-- FundedControl — v3.18.1/v3.18.2 data repair
-- Fixes: BitfundedImportController::confirm() (pre-v3.18.1) computed a matched/new
-- trade's net_pnl as `pnl - fees - COALESCE(funding, 0)`, where `funding` is that one
-- trade's own attributed slice of the account's Funding Fee history
-- (bf_attribute_funding(), bitfunded_parser.php). In the same request, confirm() also
-- writes `challenges.funding_adjustment` to the WHOLE pasted Transaction History's
-- Funding Fee total — which structurally already includes that trade's own funding as a
-- subset. helpers.php::enrichChallenge()/challengeBalance() then subtracts
-- funding_adjustment a second time on top of a net_pnl sum that already had it baked in
-- — double-counting every row this UPDATE targets. See CLAUDE.md v3.18.1 for the full
-- diagnosis (this is the ~$1.60-per-BNBUSDT-trade gap between the app's reported balance
-- and Bitfunded's own).
--
-- Fix shipped in code (BitfundedImportController::confirm()): net_pnl is now always
-- `pnl - fees`, full stop. trades.funding is kept as a display-only, informational
-- column — it no longer feeds net_pnl, and was never read by any balance/P&L sum
-- anywhere else in this codebase. challenges.funding_adjustment is untouched by this
-- file and by the code fix — its current value is already correct (it was never the
-- broken side of this bug); only the affected trades' own net_pnl needs correcting here.
--
-- v3.18.2: this file is now deployed and run through the standard migration path
-- (version.json's files -> migrate.php?mode=run), not run by hand as v3.18.1 originally
-- shipped it. That changed what belongs in this file: migrate.php executes every
-- statement in a migration through PDO::exec() (app/migrate.php::splitSqlStatements()/
-- the mode=run loop) and its own report only ever renders applied/failed + timing per
-- file — there is no code path that captures or displays a SELECT's result set. A
-- preview/verify SELECT left in this file would run against production with its output
-- going nowhere, which defeats the entire point of a "look before you touch it" preview
-- and isn't a real safeguard here. **If you want to eyeball the affected rows before
-- running this via migrate.php, run the SELECT below by hand first, via phpMyAdmin or
-- the mysql CLI** — it is intentionally not part of this file:
--
--   SELECT id, challenge_id, pair, direction, trade_date, pnl, fees, funding, net_pnl,
--          ROUND(pnl - fees, 4) AS correct_net_pnl,
--          ROUND(net_pnl - (pnl - fees), 4) AS diff
--   FROM trades
--   WHERE ABS(net_pnl - (pnl - fees)) > 0.01
--   ORDER BY challenge_id, trade_date, id;
--
-- ⚠ BACK UP THE trades TABLE BEFORE mode=run.
--   mysqldump -u <user> -p theittav_journal trades > trades_backup_2026_09_24.sql
--   (DDL/DML here can't be rolled back — same standing rule as every other migration in
--   this project, see CLAUDE.md §3A.)
--
-- The UPDATE below is the only statement in this file. It is idempotent: a trade whose
-- net_pnl is already `pnl - fees` never matches the WHERE clause, so re-running this
-- migration (or migrate.php re-running it after a prior failure, per its own
-- failed-is-retryable rule) is always safe and never a no-op-that-should-have-done-more.
-- It touches only trades.net_pnl — never pnl, fees, funding, or any challenges column
-- (funding_adjustment is untouched, exactly as documented above).
UPDATE trades
SET net_pnl = ROUND(pnl - fees, 4)
WHERE ABS(net_pnl - (pnl - fees)) > 0.01;
